services:
  # データベースサービス
  db:
    image: postgres:14
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    # データベースの健全性チェック
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Webアプリケーションサービス
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # 基本設定
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
      TZ: Asia/Tokyo
      # Active Storage設定
      ACTIVE_STORAGE_SERVICE: ${ACTIVE_STORAGE_SERVICE:-local}
      # ログ設定
      LOG_LEVEL: ${LOG_LEVEL:-debug}
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
      - bundle_data:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

# データの永続化のための設定
volumes:
  postgresql_data:
  bundle_data: