default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: 5432

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB_PRODUCTION"] %>
  username: <%= ENV["POSTGRES_USER_PRODUCTION"] %>
  password: <%= ENV["POSTGRES_PASSWORD_PRODUCTION"] %>
  host: <%= ENV["DB_HOST_PRODUCTION"] %>
