# app/models/meal_variations.rb

# 時間帯と栄養素を考慮した献立のバリエーション
module MealVariations
  # 時間帯と栄養素を考慮した献立リスト
  MEAL_VARIATIONS = {
    # 朝食の献立
    morning: {
      # 朝食×和食
      japanese: [
        { main: "焼き魚（鮭）", side: "ほうれん草のおひたし", cuisine_type: "和食", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "納豆ご飯", side: "味噌汁", cuisine_type: "和食", nutrients: [ "protein", "carbs" ] },
        { main: "卵焼き", side: "小松菜の胡麻和え", cuisine_type: "和食", nutrients: [ "protein", "vitamins" ] },
        { main: "焼き鮭", side: "わかめの酢の物", cuisine_type: "和食", nutrients: [ "protein", "minerals" ] },
        { main: "卵かけご飯", side: "のり佃煮", cuisine_type: "和食", nutrients: [ "protein", "carbs" ] },
        { main: "冷奴", side: "きんぴらごぼう", cuisine_type: "和食", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "厚揚げの煮浸し", side: "たくあん", cuisine_type: "和食", nutrients: [ "protein", "vitamins" ] },
        { main: "だし巻き卵", side: "もずく酢", cuisine_type: "和食", nutrients: [ "protein", "minerals" ] },
        { main: "さばの塩焼き", side: "野沢菜漬け", cuisine_type: "和食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "いわしの梅煮", side: "大根おろし", cuisine_type: "和食", nutrients: [ "protein", "fat", "minerals" ] },
        { main: "しらす丼", side: "冷ややっこ", cuisine_type: "和食", nutrients: [ "protein", "carbs", "minerals" ] },
        { main: "温泉卵", side: "キャベツの塩昆布和え", cuisine_type: "和食", nutrients: [ "protein", "vitamins" ] },
        { main: "鮭フレーク丼", side: "きゅうりの漬物", cuisine_type: "和食", nutrients: [ "protein", "carbs" ] },
        { main: "のり納豆", side: "わかめの味噌汁", cuisine_type: "和食", nutrients: [ "protein", "minerals" ] },
        { main: "めかぶ納豆", side: "ふりかけごはん", cuisine_type: "和食", nutrients: [ "protein", "carbs", "minerals" ] },
        { main: "あじの干物", side: "なめたけおろし", cuisine_type: "和食", nutrients: [ "protein", "minerals" ] },
        { main: "とろろご飯", side: "梅干し", cuisine_type: "和食", nutrients: [ "carbs", "minerals" ] },
        { main: "玉子粥", side: "高菜漬け", cuisine_type: "和食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "焼き鯖", side: "茄子の浅漬け", cuisine_type: "和食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "さつまいもご飯", side: "昆布の佃煮", cuisine_type: "和食", nutrients: [ "carbs", "minerals" ] },
        { main: "漬け丼", side: "わかめスープ", cuisine_type: "和食", nutrients: [ "protein", "minerals" ] },
        { main: "おかゆ", side: "梅干し", cuisine_type: "和食", nutrients: [ "carbs", "minerals" ] },
        { main: "湯豆腐", side: "菜の花のおひたし", cuisine_type: "和食", nutrients: [ "protein", "vitamins" ] },
        { main: "ツナご飯", side: "即席漬け", cuisine_type: "和食", nutrients: [ "protein", "carbs" ] },
        { main: "かつおおかか丼", side: "白菜の浅漬け", cuisine_type: "和食", nutrients: [ "protein", "vitamins" ] },
        { main: "焼き海苔ごはん", side: "オクラのおひたし", cuisine_type: "和食", nutrients: [ "carbs", "vitamins", "minerals" ] },
        { main: "鶏そぼろごはん", side: "かいわれの酢の物", cuisine_type: "和食", nutrients: [ "protein", "carbs" ] },
        { main: "たまごかけごはん", side: "昆布の佃煮", cuisine_type: "和食", nutrients: [ "protein", "carbs", "minerals" ] },
        { main: "はんぺんの焼き物", side: "モロヘイヤのおひたし", cuisine_type: "和食", nutrients: [ "protein", "vitamins" ] },
        { main: "いかの塩辛", side: "温かいごはん", cuisine_type: "和食", nutrients: [ "protein", "carbs" ] }
      ],

      # 朝食×洋食
      western: [
        { main: "ハムエッグ", side: "グリーンサラダ", cuisine_type: "洋食", nutrients: [ "protein", "vitamins" ] },
        { main: "ベーコンエッグ", side: "野菜スープ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "スクランブルエッグ", side: "トースト", cuisine_type: "洋食", nutrients: [ "protein", "carbs" ] },
        { main: "フレンチトースト", side: "ヨーグルト", cuisine_type: "洋食", nutrients: [ "carbs", "protein" ] },
        { main: "オムレツ", side: "コーンスープ", cuisine_type: "洋食", nutrients: [ "protein", "carbs" ] },
        { main: "ヨーグルト", side: "ミックスサラダ", cuisine_type: "洋食", nutrients: [ "protein", "vitamins" ] },
        { main: "シリアル", side: "フルーツ盛り合わせ", cuisine_type: "洋食", nutrients: [ "carbs", "vitamins" ] },
        { main: "クロックムッシュ", side: "アボカドサラダ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "carbs" ] },
        { main: "サンドイッチ", side: "野菜ジュース", cuisine_type: "洋食", nutrients: [ "carbs", "vitamins" ] },
        { main: "トースト", side: "コテージチーズサラダ", cuisine_type: "洋食", nutrients: [ "carbs", "protein" ] },
        { main: "パンケーキ", side: "フレッシュフルーツ", cuisine_type: "洋食", nutrients: [ "carbs", "vitamins" ] },
        { main: "ベーグル", side: "スムージー", cuisine_type: "洋食", nutrients: [ "carbs", "vitamins", "minerals" ] },
        { main: "クロワッサン", side: "プレーンヨーグルト", cuisine_type: "洋食", nutrients: [ "carbs", "protein" ] },
        { main: "モーニングプレート", side: "トマトスープ", cuisine_type: "洋食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "ソーセージエッグ", side: "グレープフルーツ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "ポーチドエッグ", side: "アスパラガスのソテー", cuisine_type: "洋食", nutrients: [ "protein", "vitamins" ] },
        { main: "グラノーラ", side: "バナナヨーグルト", cuisine_type: "洋食", nutrients: [ "carbs", "vitamins", "minerals" ] },
        { main: "エッグベネディクト", side: "レモンティー", cuisine_type: "洋食", nutrients: [ "protein", "fat", "carbs" ] },
        { main: "フルーツパンケーキ", side: "ナッツヨーグルト", cuisine_type: "洋食", nutrients: [ "carbs", "vitamins", "protein" ] },
        { main: "ホットサンド", side: "キウイフルーツ", cuisine_type: "洋食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "アボカドトースト", side: "トマトジュース", cuisine_type: "洋食", nutrients: [ "carbs", "fat", "vitamins" ] },
        { main: "マフィン", side: "フルーツヨーグルト", cuisine_type: "洋食", nutrients: [ "carbs", "vitamins" ] },
        { main: "ライ麦パン", side: "チーズオムレツ", cuisine_type: "洋食", nutrients: [ "carbs", "protein" ] },
        { main: "タマゴサンド", side: "ミネストローネ", cuisine_type: "洋食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "コーンフレーク", side: "オレンジジュース", cuisine_type: "洋食", nutrients: [ "carbs", "vitamins" ] },
        { main: "ブリオッシュ", side: "ベリースムージー", cuisine_type: "洋食", nutrients: [ "carbs", "vitamins", "minerals" ] },
        { main: "エッグマフィン", side: "ハッシュポテト", cuisine_type: "洋食", nutrients: [ "protein", "carbs" ] },
        { main: "ワッフル", side: "ミックスベリー", cuisine_type: "洋食", nutrients: [ "carbs", "vitamins" ] },
        { main: "チーズオムレツ", side: "トマトバジルサラダ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "イングリッシュマフィン", side: "リンゴのコンポート", cuisine_type: "洋食", nutrients: [ "carbs", "vitamins" ] }
      ],

      # 朝食×中華
      chinese: [
        { main: "お粥", side: "ザーサイ", cuisine_type: "中華", nutrients: [ "carbs", "minerals" ] },
        { main: "中華風卵スープ", side: "搾菜", cuisine_type: "中華", nutrients: [ "protein", "vitamins" ] },
        { main: "胡麻団子", side: "杏仁豆腐", cuisine_type: "中華", nutrients: [ "carbs", "fat", "protein" ] },
        { main: "豆乳スープ", side: "きゅうりの中華漬け", cuisine_type: "中華", nutrients: [ "protein", "vitamins" ] },
        { main: "中華風茶碗蒸し", side: "もやしのナムル", cuisine_type: "中華", nutrients: [ "protein", "vitamins" ] },
        { main: "マーボー豆腐（朝食軽め版）", side: "春雨サラダ", cuisine_type: "中華", nutrients: [ "protein", "carbs" ] },
        { main: "中華風雑炊", side: "キャベツの塩昆布和え", cuisine_type: "中華", nutrients: [ "carbs", "vitamins" ] },
        { main: "肉まん", side: "中華風サラダ", cuisine_type: "中華", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "中華粥", side: "ザーサイのナムル", cuisine_type: "中華", nutrients: [ "carbs", "minerals", "vitamins" ] },
        { main: "豆乳入りおかゆ", side: "きくらげの和え物", cuisine_type: "中華", nutrients: [ "carbs", "protein", "minerals" ] },
        { main: "蒸しパン（饅頭）", side: "ピータン豆腐", cuisine_type: "中華", nutrients: [ "carbs", "protein" ] },
        { main: "皮蛋粥", side: "搾菜", cuisine_type: "中華", nutrients: [ "carbs", "protein", "minerals" ] },
        { main: "豆漿（豆乳）", side: "油条（揚げパン）", cuisine_type: "中華", nutrients: [ "protein", "carbs" ] },
        { main: "蛋餅（卵焼き）", side: "中華風漬物", cuisine_type: "中華", nutrients: [ "protein", "vitamins" ] },
        { main: "菜包（野菜まん）", side: "ザーサイスープ", cuisine_type: "中華", nutrients: [ "carbs", "vitamins" ] },
        { main: "豆腐花", side: "きくらげサラダ", cuisine_type: "中華", nutrients: [ "protein", "minerals" ] },
        { main: "米粉粥", side: "中華風ピクルス", cuisine_type: "中華", nutrients: [ "carbs", "vitamins" ] },
        { main: "葱油餅（葱入り餅）", side: "わかめのスープ", cuisine_type: "中華", nutrients: [ "carbs", "minerals" ] },
        { main: "豆沙包（あんまん）", side: "ゆで卵", cuisine_type: "中華", nutrients: [ "carbs", "protein" ] },
        { main: "魚香茶碗蒸し", side: "きゅうりの浅漬け", cuisine_type: "中華", nutrients: [ "protein", "vitamins" ] },
        { main: "点心セット", side: "中華風コーンスープ", cuisine_type: "中華", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "シウマイ", side: "もやしの中華和え", cuisine_type: "中華", nutrients: [ "protein", "vitamins" ] },
        { main: "ビーフン", side: "クラゲの和え物", cuisine_type: "中華", nutrients: [ "carbs", "minerals" ] },
        { main: "蒸し餃子", side: "中華風卵スープ", cuisine_type: "中華", nutrients: [ "protein", "carbs" ] },
        { main: "八宝粥", side: "砂肝の炒め物", cuisine_type: "中華", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "花巻（花饅頭）", side: "くらげのサラダ", cuisine_type: "中華", nutrients: [ "carbs", "minerals" ] },
        { main: "塩粥", side: "中華風キュウリ", cuisine_type: "中華", nutrients: [ "carbs", "vitamins" ] },
        { main: "豆乳スープ", side: "ザーサイ", cuisine_type: "中華", nutrients: [ "protein", "minerals" ] },
        { main: "山東饅頭", side: "中華風わかめサラダ", cuisine_type: "中華", nutrients: [ "carbs", "minerals" ] },
        { main: "黒ゴマ粥", side: "豆腐の中華和え", cuisine_type: "中華", nutrients: [ "carbs", "protein", "minerals" ] }
      ]
    },

    # 昼食の献立
    afternoon: {
      # 昼食×和食
      japanese: [
        { main: "親子丼", side: "ほうれん草のおひたし", cuisine_type: "和食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "肉うどん", side: "きゅうりとわかめの酢の物", cuisine_type: "和食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "鮭の塩焼き", side: "ひじきの煮物", cuisine_type: "和食", nutrients: [ "protein", "minerals" ] },
        { main: "鶏の唐揚げ", side: "大根サラダ", cuisine_type: "和食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "豚の生姜焼き", side: "冷奴", cuisine_type: "和食", nutrients: [ "protein", "fat" ] },
        { main: "さばの味噌煮", side: "小松菜のお浸し", cuisine_type: "和食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "かつ丼", side: "もやしのナムル", cuisine_type: "和食", nutrients: [ "protein", "carbs", "fat" ] },
        { main: "牛丼", side: "わかめの酢の物", cuisine_type: "和食", nutrients: [ "protein", "carbs" ] },
        { main: "天ぷら盛り合わせ", side: "切干大根の煮物", cuisine_type: "和食", nutrients: [ "protein", "fat", "minerals" ] },
        { main: "鯖の塩焼き", side: "きんぴらごぼう", cuisine_type: "和食", nutrients: [ "protein", "fat", "minerals", "vitamins" ] },
        { main: "鶏そぼろ丼", side: "茄子の煮浸し", cuisine_type: "和食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "牛肉のすき煮", side: "ほうれん草の胡麻和え", cuisine_type: "和食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "鰯の梅煮", side: "冬瓜の煮物", cuisine_type: "和食", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "キーマカレー", side: "福神漬け", cuisine_type: "和食", nutrients: [ "protein", "carbs", "fat" ] },
        { main: "焼きそば", side: "冷奴", cuisine_type: "和食", nutrients: [ "carbs", "protein" ] },
        { main: "たぬきそば", side: "いんげんの胡麻和え", cuisine_type: "和食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "かけうどん", side: "野菜の天ぷら", cuisine_type: "和食", nutrients: [ "carbs", "fat", "vitamins" ] },
        { main: "ちらし寿司", side: "豆腐とわかめの味噌汁", cuisine_type: "和食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "鶏塩ラーメン", side: "もやしのナムル", cuisine_type: "和食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "味噌煮込みうどん", side: "たくあん", cuisine_type: "和食", nutrients: [ "carbs", "protein", "minerals" ] },
        { main: "豚丼", side: "キャベツの千切り", cuisine_type: "和食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "うな丼", side: "小松菜のお浸し", cuisine_type: "和食", nutrients: [ "protein", "fat", "carbs", "vitamins" ] },
        { main: "海鮮丼", side: "味噌汁", cuisine_type: "和食", nutrients: [ "protein", "carbs", "minerals" ] },
        { main: "冷やし中華", side: "枝豆", cuisine_type: "和食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "鍋焼きうどん", side: "小鉢の漬物", cuisine_type: "和食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "きつねうどん", side: "ブロッコリーのおかか和え", cuisine_type: "和食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "炊き込みご飯", side: "アサリの味噌汁", cuisine_type: "和食", nutrients: [ "carbs", "protein", "minerals" ] },
        { main: "オムライス", side: "キャベツのみそ汁", cuisine_type: "和食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "豚カツ丼", side: "大根おろし", cuisine_type: "和食", nutrients: [ "protein", "carbs", "fat" ] },
        { main: "鶏釜飯", side: "なめこおろし", cuisine_type: "和食", nutrients: [ "carbs", "protein", "minerals" ] }
      ],

      # 昼食×洋食
      western: [
        { main: "ハンバーグ", side: "コールスローサラダ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "オムライス", side: "コーンスープ", cuisine_type: "洋食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "クリームパスタ", side: "グリーンサラダ", cuisine_type: "洋食", nutrients: [ "carbs", "fat", "vitamins" ] },
        { main: "チキンカツ", side: "マカロニサラダ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "carbs" ] },
        { main: "ビーフシチュー", side: "ガーリックトースト", cuisine_type: "洋食", nutrients: [ "protein", "fat", "carbs" ] },
        { main: "ピザトースト", side: "カプレーゼ", cuisine_type: "洋食", nutrients: [ "carbs", "fat", "vitamins" ] },
        { main: "ミートソースパスタ", side: "カリフラワーサラダ", cuisine_type: "洋食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "豚カツ", side: "温野菜サラダ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "チキンソテー", side: "ジャーマンポテト", cuisine_type: "洋食", nutrients: [ "protein", "carbs", "fat" ] },
        { main: "ハムサンドイッチ", side: "野菜スープ", cuisine_type: "洋食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "グラタン", side: "トマトスープ", cuisine_type: "洋食", nutrients: [ "fat", "carbs", "vitamins" ] },
        { main: "ドライカレー", side: "フレッシュサラダ", cuisine_type: "洋食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "タコライス", side: "コンソメスープ", cuisine_type: "洋食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "ロコモコ", side: "コーンサラダ", cuisine_type: "洋食", nutrients: [ "protein", "carbs", "fat", "vitamins" ] },
        { main: "ミートローフ", side: "人参のグラッセ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "ナポリタン", side: "ほうれん草のソテー", cuisine_type: "洋食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "シーフードパスタ", side: "ニース風サラダ", cuisine_type: "洋食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "ロースとカツレツ", side: "アスパラガスのソテー", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "ハヤシライス", side: "ポテトサラダ", cuisine_type: "洋食", nutrients: [ "carbs", "protein", "fat" ] },
        { main: "キッシュ", side: "かぼちゃのポタージュ", cuisine_type: "洋食", nutrients: [ "fat", "protein", "vitamins" ] },
        { main: "ホットドッグ", side: "ミネストローネ", cuisine_type: "洋食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "BLTサンドイッチ", side: "クラムチャウダー", cuisine_type: "洋食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "タンドリーチキン", side: "ピラフ", cuisine_type: "洋食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "ビーフストロガノフ", side: "サワークラフト", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "エビフライ", side: "コーンクリームスープ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "ラザニア", side: "ズッキーニグリル", cuisine_type: "洋食", nutrients: [ "carbs", "fat", "protein", "vitamins" ] },
        { main: "スパゲッティカルボナーラ", side: "ルッコラサラダ", cuisine_type: "洋食", nutrients: [ "carbs", "fat", "protein", "vitamins" ] },
        { main: "シチリア風ピザ", side: "レンズ豆のスープ", cuisine_type: "洋食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "ビーフスパゲッティ", side: "チーズサラダ", cuisine_type: "洋食", nutrients: [ "carbs", "protein", "fat" ] },
        { main: "チーズフォンデュ", side: "ベジタブルスティック", cuisine_type: "洋食", nutrients: [ "fat", "protein", "vitamins" ] }
      ],

      # 昼食×中華
      chinese: [
        { main: "麻婆豆腐", side: "春雨サラダ", cuisine_type: "中華", nutrients: [ "protein", "fat", "carbs" ] },
        { main: "炒飯", side: "わかめスープ", cuisine_type: "中華", nutrients: [ "carbs", "protein", "minerals" ] },
        { main: "担々麺", side: "ザーサイ", cuisine_type: "中華", nutrients: [ "carbs", "protein", "fat" ] },
        { main: "回鍋肉", side: "きゅうりの中華漬け", cuisine_type: "中華", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "青椒肉絲", side: "もやしのナムル", cuisine_type: "中華", nutrients: [ "protein", "vitamins" ] },
        { main: "エビチリ", side: "中華風コーンスープ", cuisine_type: "中華", nutrients: [ "protein", "fat" ] },
        { main: "八宝菜", side: "中華風サラダ", cuisine_type: "中華", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "酢豚", side: "キャベツの塩昆布和え", cuisine_type: "中華", nutrients: [ "protein", "carbs", "fat" ] },
        { main: "海老焼売", side: "チンゲン菜の炒め物", cuisine_type: "中華", nutrients: [ "protein", "vitamins" ] },
        { main: "春巻き", side: "ナムル", cuisine_type: "中華", nutrients: [ "carbs", "fat", "vitamins" ] },
        { main: "中華丼", side: "中華風サラダ", cuisine_type: "中華", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "肉団子の甘酢あん", side: "きくらげの和え物", cuisine_type: "中華", nutrients: [ "protein", "carbs", "minerals" ] },
        { main: "エビマヨ", side: "中華スープ", cuisine_type: "中華", nutrients: [ "protein", "fat" ] },
        { main: "豚バラ肉の角煮", side: "もやしとニラのナムル", cuisine_type: "中華", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "揚げ餃子", side: "ザーサイの和え物", cuisine_type: "中華", nutrients: [ "carbs", "protein", "minerals" ] },
        { main: "五目焼きそば", side: "搾菜", cuisine_type: "中華", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "麻婆ナス", side: "白菜スープ", cuisine_type: "中華", nutrients: [ "fat", "vitamins", "minerals" ] },
        { main: "鶏の唐揚げ 香味ソース", side: "くらげの和え物", cuisine_type: "中華", nutrients: [ "protein", "fat", "minerals" ] },
        { main: "干し豆腐の炒め物", side: "烏龍茶", cuisine_type: "中華", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "小籠包", side: "わかめと卵のスープ", cuisine_type: "中華", nutrients: [ "protein", "carbs", "minerals" ] },
        { main: "什錦炒麺（五目焼きそば）", side: "ザーサイのみじん切り", cuisine_type: "中華", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "牛肉のオイスターソース炒め", side: "中華風サラダ", cuisine_type: "中華", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "海鮮チャーハン", side: "豆腐スープ", cuisine_type: "中華", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "冷やし坦々麺", side: "杏仁豆腐", cuisine_type: "中華", nutrients: [ "carbs", "protein", "fat" ] },
        { main: "四川風麻婆豆腐", side: "中華風コールスロー", cuisine_type: "中華", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "蝦仁炒飯（エビチャーハン）", side: "キノコのスープ", cuisine_type: "中華", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "北京ダック", side: "もやしの和え物", cuisine_type: "中華", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "蟹肉入り玉子スープ", side: "パオズ（中華まん）", cuisine_type: "中華", nutrients: [ "protein", "carbs", "minerals" ] },
        { main: "白身魚の甘酢あんかけ", side: "中華風茶碗蒸し", cuisine_type: "中華", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "汁なし担々麺", side: "ザーサイともやしの和え物", cuisine_type: "中華", nutrients: [ "carbs", "protein", "fat" ] }
      ]
    },

    # 夕食の献立
    evening: {
      # 夕食×和食
      japanese: [
        { main: "すき焼き", side: "菜の花の辛子和え", cuisine_type: "和食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "肉じゃが", side: "ほうれん草の胡麻和え", cuisine_type: "和食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "ぶりの照り焼き", side: "切干大根の煮物", cuisine_type: "和食", nutrients: [ "protein", "fat", "minerals" ] },
        { main: "焼き鮭", side: "大根の煮物", cuisine_type: "和食", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "豚の角煮", side: "小松菜と油揚げの煮浸し", cuisine_type: "和食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "筑前煮", side: "きゅうりの浅漬け", cuisine_type: "和食", nutrients: [ "protein", "carbs", "vitamins", "minerals" ] },
        { main: "さんまの塩焼き", side: "なめこおろし", cuisine_type: "和食", nutrients: [ "protein", "fat", "minerals" ] },
        { main: "鶏の照り焼き", side: "根菜のきんぴら", cuisine_type: "和食", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "ぶり大根", side: "菜の花のおひたし", cuisine_type: "和食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "おでん", side: "春菊のおひたし", cuisine_type: "和食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "鯛の煮付け", side: "きゅうりとわかめの酢の物", cuisine_type: "和食", nutrients: [ "protein", "minerals", "vitamins" ] },
        { main: "焼き鳥丼", side: "茄子の揚げ浸し", cuisine_type: "和食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "牛肉とごぼうの甘辛煮", side: "ブロッコリーのおかか和え", cuisine_type: "和食", nutrients: [ "protein", "minerals", "vitamins" ] },
        { main: "さわらの西京焼き", side: "さつまいもの甘煮", cuisine_type: "和食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "しゃぶしゃぶ", side: "春雨サラダ", cuisine_type: "和食", nutrients: [ "protein", "fat", "carbs" ] },
        { main: "鯵のたたき", side: "かぼちゃの煮物", cuisine_type: "和食", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "寄せ鍋", side: "きゅうりともやしの酢の物", cuisine_type: "和食", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "かつおのたたき", side: "ごぼうサラダ", cuisine_type: "和食", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "鱈の煮付け", side: "ひじきと大豆の煮物", cuisine_type: "和食", nutrients: [ "protein", "minerals", "vitamins" ] },
        { main: "鯖の味噌煮", side: "ほうれん草の白和え", cuisine_type: "和食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "焼きうどん", side: "茶碗蒸し", cuisine_type: "和食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "うなぎの蒲焼", side: "オクラのおひたし", cuisine_type: "和食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "鮭のちゃんちゃん焼き", side: "里芋の煮っころがし", cuisine_type: "和食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "鶏肉と野菜の治部煮", side: "大根の味噌汁", cuisine_type: "和食", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "たらのホイル焼き", side: "がんもどきの煮物", cuisine_type: "和食", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "豚バラ肉と白菜の重ね蒸し", side: "わかめとえのきの酢の物", cuisine_type: "和食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "いわしのつみれ汁", side: "れんこんのきんぴら", cuisine_type: "和食", nutrients: [ "protein", "minerals", "vitamins" ] },
        { main: "ちゃんこ鍋", side: "きゅうりの漬物", cuisine_type: "和食", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "ほっけの塩焼き", side: "茄子の味噌炒め", cuisine_type: "和食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "たこの煮物", side: "モロヘイヤのおひたし", cuisine_type: "和食", nutrients: [ "protein", "vitamins", "minerals" ] }
      ],

      # 夕食×洋食
      western: [
        { main: "ビーフシチュー", side: "グリーンサラダ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "ハンバーグ", side: "マッシュポテト", cuisine_type: "洋食", nutrients: [ "protein", "fat", "carbs" ] },
        { main: "チキンのトマト煮", side: "ニース風サラダ", cuisine_type: "洋食", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "ポークソテー", side: "コールスローサラダ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "カレーライス", side: "福神漬け", cuisine_type: "洋食", nutrients: [ "carbs", "protein", "fat" ] },
        { main: "クリームシチュー", side: "パンプキンサラダ", cuisine_type: "洋食", nutrients: [ "fat", "carbs", "vitamins" ] },
        { main: "ビーフステーキ", side: "温野菜サラダ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "グラタン", side: "アボカドサラダ", cuisine_type: "洋食", nutrients: [ "fat", "carbs", "vitamins" ] },
        { main: "ロールキャベツ", side: "コーンスープ", cuisine_type: "洋食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "チキンカレー", side: "フレッシュサラダ", cuisine_type: "洋食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "ラザニア", side: "キノコのソテー", cuisine_type: "洋食", nutrients: [ "carbs", "protein", "fat" ] },
        { main: "ミートローフ", side: "ブロッコリーのグラタン", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "ポークチョップ", side: "ハーブポテト", cuisine_type: "洋食", nutrients: [ "protein", "fat", "carbs" ] },
        { main: "ビーフカレー", side: "レーズンサラダ", cuisine_type: "洋食", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "チキンピカタ", side: "トマトスープ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "シーフードリゾット", side: "フェンネルのサラダ", cuisine_type: "洋食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "牛肉のボルシチ", side: "ガーリックブレッド", cuisine_type: "洋食", nutrients: [ "protein", "vitamins", "carbs" ] },
        { main: "ポトフ", side: "カマンベールチーズ", cuisine_type: "洋食", nutrients: [ "protein", "vitamins", "fat" ] },
        { main: "サーモンのムニエル", side: "グリーンアスパラガス", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "ビーフストロガノフ", side: "ライスピラフ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "carbs" ] },
        { main: "チキンのコルドンブルー", side: "トマトとバジルのサラダ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "パエリア", side: "ガスパチョ", cuisine_type: "洋食", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "牛肉のストロガノフ", side: "キャロットラペ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "ビーフブルギニョン", side: "ポテトグラタン", cuisine_type: "洋食", nutrients: [ "protein", "fat", "carbs" ] },
        { main: "チキンのコンフィ", side: "ラタトゥイユ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "オセール風ビーフシチュー", side: "エンダイブのサラダ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "ポークソテー マスタードソース", side: "ロメインレタスのシーザーサラダ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "ハニーマスタードチキン", side: "温野菜のガーリックソテー", cuisine_type: "洋食", nutrients: [ "protein", "vitamins", "fat" ] },
        { main: "ビーフストロガノフ", side: "焼きナス", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "ラムチョップ", side: "タブレサラダ", cuisine_type: "洋食", nutrients: [ "protein", "fat", "vitamins" ] }
      ],

      # 夕食×中華
      chinese: [
        { main: "麻婆豆腐", side: "春雨サラダ", cuisine_type: "中華", nutrients: [ "protein", "fat", "carbs" ] },
        { main: "酢豚", side: "中華スープ", cuisine_type: "中華", nutrients: [ "protein", "fat", "carbs" ] },
        { main: "回鍋肉", side: "きゅうりの中華漬け", cuisine_type: "中華", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "八宝菜", side: "もやしのナムル", cuisine_type: "中華", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "エビチリ", side: "青梗菜の炒め物", cuisine_type: "中華", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "豚の角煮", side: "中華風コーンスープ", cuisine_type: "中華", nutrients: [ "protein", "fat", "carbs" ] },
        { main: "青椒肉絲", side: "卵スープ", cuisine_type: "中華", nutrients: [ "protein", "vitamins" ] },
        { main: "麻婆茄子", side: "わかめと卵のスープ", cuisine_type: "中華", nutrients: [ "fat", "protein", "vitamins" ] },
        { main: "油淋鶏", side: "豆腐のスープ", cuisine_type: "中華", nutrients: [ "protein", "fat" ] },
        { main: "海老のチリソース煮", side: "中華風サラダ", cuisine_type: "中華", nutrients: [ "protein", "vitamins" ] },
        { main: "うま煮", side: "ザーサイの和え物", cuisine_type: "中華", nutrients: [ "protein", "fat", "minerals" ] },
        { main: "北京ダック", side: "ホタテのスープ", cuisine_type: "中華", nutrients: [ "protein", "fat" ] },
        { main: "チンジャオロース", side: "大根とキクラゲの和え物", cuisine_type: "中華", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "豚肉の甘酢あんかけ", side: "ザーサイとキュウリの和え物", cuisine_type: "中華", nutrients: [ "protein", "carbs", "vitamins" ] },
        { main: "麻婆春雨", side: "チンゲン菜の塩炒め", cuisine_type: "中華", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "黒酢の酢豚", side: "蟹と豆腐のスープ", cuisine_type: "中華", nutrients: [ "protein", "fat", "carbs" ] },
        { main: "四川風牛肉の炒め物", side: "きくらげと卵のスープ", cuisine_type: "中華", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "魚の甘酢あんかけ", side: "ワンタンスープ", cuisine_type: "中華", nutrients: [ "protein", "carbs", "minerals" ] },
        { main: "什景炒飯", side: "タケノコの中華スープ", cuisine_type: "中華", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "鶏肉のカシューナッツ炒め", side: "トマトと卵のスープ", cuisine_type: "中華", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "豚肉と茄子の味噌炒め", side: "なめこと豆腐のスープ", cuisine_type: "中華", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "チャーシュー", side: "エビとブロッコリーの炒め物", cuisine_type: "中華", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "麻辣湯（マーラータン）", side: "白菜の漬物", cuisine_type: "中華", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "牛肉ときのこの中華炒め", side: "かに玉スープ", cuisine_type: "中華", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "海鮮と野菜の塩炒め", side: "冬瓜のスープ", cuisine_type: "中華", nutrients: [ "protein", "vitamins", "minerals" ] },
        { main: "炸醤麺（ジャージャー麺）", side: "杏仁豆腐", cuisine_type: "中華", nutrients: [ "carbs", "protein", "fat" ] },
        { main: "東坡肉（トンポーロー）", side: "白菜の漬物", cuisine_type: "中華", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "叉焼飯（チャーシューチャーハン）", side: "もやしとニラの炒め物", cuisine_type: "中華", nutrients: [ "carbs", "protein", "vitamins" ] },
        { main: "鶏肉の四川風辛味ソース", side: "中華風温野菜サラダ", cuisine_type: "中華", nutrients: [ "protein", "fat", "vitamins" ] },
        { main: "上海風かに玉", side: "酸辣湯（サンラータン）", cuisine_type: "中華", nutrients: [ "protein", "fat", "minerals" ] }
      ]
    }
  }
end
